---
title: "Assessment 1"
author: "Oksana Kuchma 4661806"
date: "28/08/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# **R Markdown editing** 
## R Markdown is a file format for making dynamic documents with R. An *R Markdown* document is written in markdown **(an easy-to-write plain text format)**

```{r fastfood}
fastfood <-read.csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2018/2018-09-04/fastfood_calories.csv")
```
#** apply libarary
```{r}
library(tidyverse)
library(skimr)
library(knitr)
library(janitor)
library(dplyr)
library(ggplot2)
```

```{r}

fastfood10 <- fastfood %>% head(10) #displaying first 10 rows of fastfood.
```


```{r 2}
knitr::kable(fastfood10 [, 1:5]) #displaying first 10 rows and 5 variables
```

```{r 3}
fastfood10 %>% filter( calories>1000) #displaying calories more than 1000
```

```{r 4}
dont_eat_this <- fastfood10 %>% filter(total_fat>40 & total_carb>80) #displaying the observations with total fat > 40 and total_card>80 and assigned to variable dont_eat_this
```

```{r 5}

Mcdonalds <-  fastfood %>% filter(restaurant == "Mcdonalds") #displaying restaurant mcdonalds
```

```{r skimr}
library(skimr)
Variables <- skim(fastfood) %>%
  dplyr::select(skim_variable)
```

```{r counting}
fastfood %>%
  count(restaurant, sort = TRUE) %>%
  kable()
```

```{r grouping}
averagecalories <- fastfood %>%
  group_by(restaurant) %>%
  summarise(average_calories = mean(calories))

```

```{r mutating}
average_calories <- fastfood %>%
  group_by(restaurant) %>%
  mutate(average_calories = mean(calories)) %>%
  ungroup() 
```

```{r fat}
average_calories %>% 
  group_by(restaurant) %>% 
  summarise(mean(total_fat))
```


```{r mutating fat}
average_fat <- average_calories %>%
  group_by(restaurant) %>%
  mutate(average_fat = mean(total_fat)) %>%
  ungroup()
```

```{r}
ggplot(Mcdonalds, aes(x = sugar, y = protein)) +
  geom_point(color = "purple")
```
 #Assessmet part 3

```{r factor}
class (fastfood$restaurant)  
fastfood2 <- as_factor(fastfood$restaurant)
calories_type <- cut_number(fastfood$calories, n = 3, labels=c("low", "med", "high"))
levels(calories_type)
fastfood2 <- fastfood %>% mutate(fct_relevel(calories_type))
```

```{r}
fastfood %>% ggplot (aes(calories_type,restaurant,)) + geom_col() + 
coord_flip() +
facet_wrap(~restaurant) +
theme_linedraw()
```

```{r}
fastfood <- fastfood %>% mutate(trans_fat_percent = trans_fat/total_fat * 100)
```

```{r}
ggplot(fastfood, aes(trans_fat_percent,restaurant,fill = restaurant)) + 
  geom_col() +
  coord_flip() +
  theme_linedraw()
```

```{r}
totalfat <- fastfood %>%
  group_by(restaurant) %>%
  summarise(total_fat = mean(total_fat))
```

```{r}
totalfat <- fastfood %>%
  group_by(restaurant) %>%
  summarise(total_fat = mean(total_fat))
```

```{r totalfat plot}

 ggplot(totalfat, aes(total_fat, restaurant, fill = restaurant)) +
  geom_col()

```
